openapi: 3.0.0
info:
  description: An app that receives and analyzes the readings of "temperature", "air pressure" of the Earth from space centres
  version: "1.0.0"
  title: Space API
  contact:
    email: gkamboj5@my.bcit.ca
tags:
  - name: sensors
    description: Operations available to space centres
paths:
  /data/temperature:

    get:
      tags:
        - sensors
      summary: gets new temperature data
      operationId: app.get_temperature_data
      description: Gets temperature data between start_timestamp and end_timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of items on the page
          schema:
            type: string
            format: date-time
            example: '2016-08-29T09:12:33Z'
        - name: end_timestamp
          in: query
          description: Limits the number of items on the page
          schema:
            type: string
            format: date-time
            example: '2020-08-29T09:12:33Z'
      responses:
        '200':
          description: Successfully returned a list of temperature events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TemperatureData'
        '400':
          description: 'Invalid/Bad Request'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        
  /data/air-pressure:
  
    get:
      tags:
        - sensors
      summary: gets new air pressure data
      operationId: app.get_air_pressure_data
      description: Gets air pressure data between start_timestamp and end_timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of items on the page
          schema:
            type: string
            format: date-time
            example: '2016-08-29T09:12:33Z'
        - name: end_timestamp
          in: query
          description: Limits the number of items on the page
          schema:
            type: string
            format: date-time
            example: '2020-08-29T09:12:33Z'
      responses:
        '200':
          description: Successfully returned a list of air pressure events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AirPressureData'
        '400':
          description: 'Invalid/Bad Request'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    TemperatureData:
      required:
        - sensor_id
        - coordinates
        - temperature
        - timestamp
      properties:
        sensor_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        coordinates:
          type: string
          example: "36.61, 0.78"
        temperature:
          $ref: '#/components/schemas/Temperature'
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
      type: object
  
  
    AirPressureData:
      required:
        - sensor_id
        - coordinates
        - air_pressure
        - timestamp
      properties:
        sensor_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        coordinates:
          type: string
          example: "36.61, 0.78"
        air_pressure:
          type: string
          example: "102.2kPa"
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
      type: object
      
    Temperature:
      required:
      - low
      - intermediate
      - high
      properties:
        low:
          type: string
          example: "10°C"
        intermediate:
          type: string
          example: "22°C"
        high:
          type: string
          example: "40°C"
      type: object
      